# Generated by Django 5.2.11 on 2026-03-03 12:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('vendeur', 'Vendeur'), ('entreprise', 'Entreprise de livraison'), ('livreur', 'Livreur'), ('admin', 'Administrateur')], default='vendeur', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('is_approved', models.BooleanField(default=False, verbose_name="Approuvé par l'admin")),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de vérification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('forme_juridique', models.CharField(choices=[('sarl', 'SARL'), ('sa', 'SA'), ('suarl', 'SUARL'), ('autre', 'Autre')], max_length=20, verbose_name='Forme juridique')),
                ('matricule_fiscal', models.CharField(max_length=50, verbose_name='Matricule fiscal')),
                ('annee_creation', models.PositiveIntegerField(verbose_name='Année de création')),
                ('adresse_siege', models.TextField(verbose_name='Adresse du siège')),
                ('gouvernorat', models.CharField(max_length=100, verbose_name='Gouvernorat')),
                ('responsable_nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('responsable_prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('responsable_poste', models.CharField(max_length=100, verbose_name='Poste')),
                ('responsable_tel', models.CharField(max_length=20, verbose_name='Tél direct')),
                ('nombre_livreurs', models.PositiveIntegerField(default=0)),
                ('capacite_journaliere', models.PositiveIntegerField(default=0, verbose_name='Capacité journalière (colis)')),
                ('zones_couverture', models.JSONField(default=list)),
                ('types_colis_acceptes', models.JSONField(default=list)),
                ('modes_livraison', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Entreprise',
                'verbose_name_plural': 'Profils Entreprises',
            },
        ),
        migrations.CreateModel(
            name='VendeurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=200, verbose_name='Nom de la boutique')),
                ('secteur', models.CharField(choices=[('mode', 'Mode et Vetements'), ('electronique', 'Electronique'), ('alimentaire', 'Alimentaire'), ('beaute', 'Beaute et Cosmetiques'), ('maison', 'Maison et Decoration'), ('sport', 'Sport et Loisirs'), ('autre', 'Autre')], max_length=50, verbose_name="Secteur d'activité")),
                ('volume_mensuel', models.PositiveIntegerField(default=0, verbose_name='Volume mensuel estimé (colis)')),
                ('adresse_expedition', models.TextField(verbose_name='Adresse')),
                ('gouvernorat', models.CharField(max_length=100, verbose_name='Gouvernorat')),
                ('delegation', models.CharField(max_length=100, verbose_name='Délégation')),
                ('numero_rc', models.CharField(blank=True, max_length=50, verbose_name='Numéro RC')),
                ('matricule', models.CharField(blank=True, max_length=50, verbose_name='Matricule fiscal')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendeur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Vendeur',
                'verbose_name_plural': 'Profils Vendeurs',
            },
        ),
    ]
