# Generated by Django 5.2.11 on 2026-03-25 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gouvernorat', models.CharField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Ben Arous', 'Ben Arous'), ('Manouba', 'Manouba'), ('Nabeul', 'Nabeul'), ('Zaghouan', 'Zaghouan'), ('Bizerte', 'Bizerte'), ('Béja', 'Béja'), ('Jendouba', 'Jendouba'), ('Kef', 'Kef'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Monastir', 'Monastir'), ('Mahdia', 'Mahdia'), ('Sfax', 'Sfax'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Gabès', 'Gabès'), ('Médenine', 'Médenine'), ('Tataouine', 'Tataouine'), ('Gafsa', 'Gafsa'), ('Tozeur', 'Tozeur'), ('Kébili', 'Kébili')], max_length=50)),
                ('poids_min', models.FloatField()),
                ('poids_max', models.FloatField()),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('delai_jours', models.FloatField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='accounts.entrepriseprofile')),
            ],
            options={
                'unique_together': {('entreprise', 'gouvernorat', 'poids_min', 'poids_max')},
            },
        ),
    ]
