# Generated by Django 5.2.11 on 2026-04-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='delai_jours',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='poids_max',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='poids_min',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
