# Generated by Django 5.2.11 on 2026-03-12 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Référence')),
                ('dest_nom', models.CharField(max_length=100, verbose_name='Nom destinataire')),
                ('dest_prenom', models.CharField(max_length=100, verbose_name='Prénom destinataire')),
                ('dest_telephone', models.CharField(max_length=20, verbose_name='Téléphone destinataire')),
                ('dest_adresse', models.TextField(verbose_name='Adresse de livraison')),
                ('dest_gouvernorat', models.CharField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Ben Arous', 'Ben Arous'), ('Manouba', 'Manouba'), ('Nabeul', 'Nabeul'), ('Zaghouan', 'Zaghouan'), ('Bizerte', 'Bizerte'), ('Béja', 'Béja'), ('Jendouba', 'Jendouba'), ('Kef', 'Kef'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Monastir', 'Monastir'), ('Mahdia', 'Mahdia'), ('Sfax', 'Sfax'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Gabès', 'Gabès'), ('Médenine', 'Médenine'), ('Tataouine', 'Tataouine'), ('Gafsa', 'Gafsa'), ('Tozeur', 'Tozeur'), ('Kébili', 'Kébili')], max_length=50, verbose_name='Gouvernorat de livraison')),
                ('type_livraison', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('jour_j', 'Jour J'), ('nuit', 'Nuit'), ('point_relai', 'Point relais')], default='standard', max_length=20, verbose_name='Type de livraison')),
                ('montant_a_collecter', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Montant à collecter (TND)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('prise_charge', 'Prise en charge'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('retournee', 'Retournée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reference_interne', models.CharField(blank=True, max_length=100, verbose_name='Référence interne vendeur')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('vendeur', models.ForeignKey(limit_choices_to={'role': 'vendeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description du colis')),
                ('poids', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Poids (kg)')),
                ('fragile', models.BooleanField(default=False, verbose_name='Colis fragile')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='commandes.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(choices=[('en_attente', 'En attente'), ('prise_charge', 'Prise en charge'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('retournee', 'Retournée'), ('annulee', 'Annulée')], max_length=20)),
                ('nouveau_statut', models.CharField(choices=[('en_attente', 'En attente'), ('prise_charge', 'Prise en charge'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('retournee', 'Retournée'), ('annulee', 'Annulée')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='commandes.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Historique statut',
                'verbose_name_plural': 'Historiques statuts',
                'ordering': ['-date'],
            },
        ),
    ]
