# Generated by Django 5.2.11 on 2026-03-31 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiquestatut',
            options={},
        ),
        migrations.RemoveField(
            model_name='commande',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='reference_interne',
        ),
        migrations.AddField(
            model_name='commande',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='accounts.entrepriseprofile'),
        ),
        migrations.AddField(
            model_name='commande',
            name='prix_livraison',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colis',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='colis',
            name='fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colis',
            name='poids',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='commande',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dest_adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dest_gouvernorat',
            field=models.CharField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Ben Arous', 'Ben Arous'), ('Manouba', 'Manouba'), ('Nabeul', 'Nabeul'), ('Zaghouan', 'Zaghouan'), ('Bizerte', 'Bizerte'), ('Béja', 'Béja'), ('Jendouba', 'Jendouba'), ('Kef', 'Kef'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Monastir', 'Monastir'), ('Mahdia', 'Mahdia'), ('Sfax', 'Sfax'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Gabès', 'Gabès'), ('Médenine', 'Médenine'), ('Tataouine', 'Tataouine'), ('Gafsa', 'Gafsa'), ('Tozeur', 'Tozeur'), ('Kébili', 'Kébili')], max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dest_nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dest_prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dest_telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant_a_collecter',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='reference',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('prise_charge', 'Prise en charge'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('retournee', 'Retournée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type_livraison',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('jour_j', 'Jour J'), ('nuit', 'Nuit'), ('point_relai', 'Point relais')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='commandes.commande'),
        ),
    ]
