# Generated by Django 5.2.11 on 2026-03-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_alter_colis_options_alter_commande_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
