# Generated by Django 5.2.11 on 2026-03-31 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colis',
            options={'verbose_name': 'Colis', 'verbose_name_plural': 'Colis'},
        ),
        migrations.AlterModelOptions(
            name='historiquestatut',
            options={'ordering': ['-date'], 'verbose_name': 'Historique statut', 'verbose_name_plural': 'Historiques statuts'},
        ),
        migrations.AlterField(
            model_name='colis',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='commandes.commande', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description du colis'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='fragile',
            field=models.BooleanField(default=False, verbose_name='Colis fragile'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='poids',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Poids (kg)'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='vendeur',
            field=models.ForeignKey(limit_choices_to={'role': 'vendeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='commandes.commande', verbose_name='Commande'),
        ),
    ]
