# Generated by Django 5.2.11 on 2026-04-01 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_colis_options_alter_historiquestatut_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colis',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiquestatut',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='commande',
            name='reference_interne',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence interne'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='colis',
            name='fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colis',
            name='poids',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='commandes.commande'),
        ),
    ]
