# Generated by Django 5.2.11 on 2026-04-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_alter_colis_options_alter_historiquestatut_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='reference_interne',
        ),
    ]
