# Generated by Django 5.2.11 on 2026-04-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_remove_commande_reference_interne'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='dest_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude destination'),
        ),
        migrations.AddField(
            model_name='commande',
            name='dest_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude destination'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='type_livraison',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=20),
        ),
    ]
