# Generated by Django 5.2.11 on 2026-04-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_commande_dest_latitude_commande_dest_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='dest_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='dest_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
