# Generated by Django 5.2.11 on 2026-03-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
        ('commandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('cin', models.CharField(blank=True, max_length=20, verbose_name='CIN')),
                ('gouvernorats_couverts', models.JSONField(default=list, verbose_name='Gouvernorats couverts')),
                ('type_vehicule', models.CharField(blank=True, max_length=50, verbose_name='Type de véhicule')),
                ('immatriculation', models.CharField(blank=True, max_length=20, verbose_name='Immatriculation')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_tournee', 'En tournée'), ('inactif', 'Inactif')], default='disponible', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livreurs', to='accounts.entrepriseprofile', verbose_name='Entreprise')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'livreur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Référence tournée')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('zone_gouvernorat', models.CharField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Ben Arous', 'Ben Arous'), ('Manouba', 'Manouba'), ('Nabeul', 'Nabeul'), ('Zaghouan', 'Zaghouan'), ('Bizerte', 'Bizerte'), ('Béja', 'Béja'), ('Jendouba', 'Jendouba'), ('Kef', 'Kef'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Monastir', 'Monastir'), ('Mahdia', 'Mahdia'), ('Sfax', 'Sfax'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Gabès', 'Gabès'), ('Médenine', 'Médenine'), ('Tataouine', 'Tataouine'), ('Gafsa', 'Gafsa'), ('Tozeur', 'Tozeur'), ('Kébili', 'Kébili')], max_length=50, verbose_name='Zone principale')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournees', to='accounts.entrepriseprofile', verbose_name='Entreprise')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournees', to='entreprise.livreur', verbose_name='Livreur')),
            ],
            options={
                'verbose_name': 'Tournée',
                'verbose_name_plural': 'Tournées',
                'ordering': ['-date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='AffectationCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('affectee_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='commandes.commande', verbose_name='Commande')),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='entreprise.tournee', verbose_name='Tournée')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['tournee', 'ordre'],
                'unique_together': {('tournee', 'commande')},
            },
        ),
    ]
