# Generated by Django 5.2.11 on 2026-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='derniere_position',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
