# Generated by Django 5.2.11 on 2026-04-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0002_livreur_derniere_position_livreur_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournee',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='tournee',
            name='livreur',
        ),
        migrations.DeleteModel(
            name='AffectationCommande',
        ),
        migrations.DeleteModel(
            name='Tournee',
        ),
    ]
