# Generated by Django 5.2.11 on 2026-04-20 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_alter_commande_dest_latitude_and_more'),
        ('entreprise', '0003_remove_tournee_entreprise_remove_tournee_livreur_and_more'),
        ('tournees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreuveLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_preuve', models.ImageField(blank=True, null=True, upload_to='preuves/photos/%Y/%m/%d/')),
                ('commentaire_livreur', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preuve_livraison', to='commandes.commande')),
                ('tournee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preuves', to='tournees.tournee')),
            ],
            options={
                'verbose_name': 'Preuve de livraison',
                'verbose_name_plural': 'Preuves de livraison',
            },
        ),
    ]
