# Generated by Django 5.2.11 on 2026-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournee',
            name='heure_depart_reelle',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure de départ réelle'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='heure_fin_reelle',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin réelle'),
        ),
    ]
