# Generated by Django 5.2.11 on 2026-03-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores_details', models.JSONField(default=list, verbose_name='Détail des scores')),
                ('selection_manuelle', models.BooleanField(default=False, verbose_name='Sélection manuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommandation', to='commandes.commande', verbose_name='Commande')),
                ('entreprise_choisie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_choisies', to='accounts.entrepriseprofile', verbose_name='Entreprise choisie')),
                ('entreprise_recommandee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommandations_recues', to='accounts.entrepriseprofile', verbose_name='Entreprise recommandée')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gouvernorat', models.CharField(choices=[('Tunis', 'Tunis'), ('Ariana', 'Ariana'), ('Ben Arous', 'Ben Arous'), ('Manouba', 'Manouba'), ('Nabeul', 'Nabeul'), ('Zaghouan', 'Zaghouan'), ('Bizerte', 'Bizerte'), ('Béja', 'Béja'), ('Jendouba', 'Jendouba'), ('Kef', 'Kef'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Monastir', 'Monastir'), ('Mahdia', 'Mahdia'), ('Sfax', 'Sfax'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Gabès', 'Gabès'), ('Médenine', 'Médenine'), ('Tataouine', 'Tataouine'), ('Gafsa', 'Gafsa'), ('Tozeur', 'Tozeur'), ('Kébili', 'Kébili')], max_length=50, verbose_name='Gouvernorat')),
                ('poids_min', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Poids min (kg)')),
                ('poids_max', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Poids max (kg)')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Prix (TND)')),
                ('delai_jours', models.PositiveSmallIntegerField(default=2, verbose_name='Délai estimé (jours)')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='accounts.entrepriseprofile', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'ordering': ['entreprise', 'gouvernorat', 'poids_min'],
                'unique_together': {('entreprise', 'gouvernorat', 'poids_min', 'poids_max')},
            },
        ),
    ]
