# Generated by Django 5.2.11 on 2026-03-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarif',
        ),
    ]
