# Generated by Django 5.2.11 on 2026-03-31 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(max_length=30)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email + SMS')], max_length=10)),
                ('destinataire', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('echoue', 'Échoué'), ('simule', 'Simulé')], max_length=10)),
                ('erreur', models.TextField(blank=True)),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_client', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Notification client',
                'verbose_name_plural': 'Notifications client',
                'ordering': ['-envoye_le'],
            },
        ),
    ]
