# Generated by Django 5.2.11 on 2026-03-31 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('notifications_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationclient',
            options={'ordering': ['-envoye_le']},
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='sms', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sms', to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='statut',
            field=models.CharField(choices=[('envoye', 'Envoyé'), ('echoue', 'Échoué')], max_length=10),
        ),
    ]
