# Generated by Django 5.2.11 on 2026-04-01 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_remove_commande_reference_interne'),
        ('notifications_client', '0002_alter_notificationclient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationclient',
            options={'ordering': ['-envoye_le'], 'verbose_name': 'Notification client', 'verbose_name_plural': 'Notifications client'},
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email + SMS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_client', to='commandes.commande'),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='destinataire',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='statut',
            field=models.CharField(choices=[('envoye', 'Envoye'), ('echec', 'Echec')], max_length=10),
        ),
        migrations.CreateModel(
            name='ConfigNotificationVendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email uniquement'), ('sms', 'SMS uniquement'), ('both', 'Email + SMS'), ('none', 'Desactive')], default='both', max_length=10)),
                ('modele_email', models.TextField(blank=True)),
                ('modele_sms', models.CharField(blank=True, max_length=320)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendeur', models.OneToOneField(limit_choices_to={'role': 'vendeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='config_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config notification vendeur',
            },
        ),
    ]
