# Generated by Django 5.2.11 on 2026-04-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_client', '0003_alter_notificationclient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationclient',
            name='canal',
            field=models.CharField(choices=[('sms', 'SMS')], default='sms', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationclient',
            name='statut',
            field=models.CharField(choices=[('envoye', 'Envoyé'), ('echec', 'Échec')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ConfigNotificationVendeur',
        ),
    ]
