# Generated by Django 5.2.11 on 2026-03-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('client_absent', 'Client absent'), ('injoignable', 'Injoignable'), ('refus_client', 'Refus du client'), ('adresse_invalide', 'Adresse invalide'), ('autre', 'Autre')], max_length=30, verbose_name='Motif du retour')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire livreur')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de retour'), ('recu_depot', 'Reçu au dépôt'), ('reprogramme', 'Reprogrammé'), ('annule_final', 'Annulé définitivement')], default='en_cours', max_length=20, verbose_name='Statut du retour')),
                ('decision_vendeur', models.CharField(blank=True, choices=[('reprogrammer', 'Reprogrammer'), ('annuler', 'Annuler')], max_length=20, verbose_name='Décision vendeur')),
                ('notes_vendeur', models.TextField(blank=True, verbose_name='Notes vendeur')),
                ('date_retour', models.DateTimeField(auto_now_add=True, verbose_name='Date du retour')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retour', to='commandes.commande', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Retour commande',
                'verbose_name_plural': 'Retours commandes',
                'ordering': ['-date_retour'],
            },
        ),
    ]
